[build.targets.wheel]
only-include = ["pydra/tasks/dcm2bids"]

[envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
]
[envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=pydra --cov=tests {args}"
no-cov = "cov --no-cov {args}"

[[envs.test.matrix]]
python = ["3.7", "3.8", "3.9", "3.10", "3.11"]

[envs.lint]
detached = true
dependencies = [
  "black",
  "isort",
  "tomli",
]
[envs.lint.scripts]
all = [
  "black --check --diff pydra",
  "isort --check --diff pydra",
]
fix = [
  "black --quiet pydra",
  "isort --quiet pydra",
]

[envs.docs]
template = "docs"
dependencies = [
  "pydata-sphinx-theme",
  "sphinx <7",
  "sphinx-autobuild",
  "sphinx-pyproject",
]
[envs.docs.scripts]
build = "sphinx-build -M {args:html} docs docs/_build"
serve = "sphinx-autobuild docs docs/_build/html {args}"
